### ISSUE TITLE
[Feat] iOS 2차 과제 🍎

### ISSUE THREAD

**Issue by 0lynny** [GO-SOPT-iOS-Part/ChoiYoungLyn#3]
## 💡 Issue

iOS 2차 과제 - 티빙 클론코딩

## ✅ To-do List

🍎 기본과제
- [x] 티빙 UI 구현
- [x] 티빙 로그인 기능 구현

🍎 도전과제
- [x] 바텀시트로 닉네임 설정 기능 구현
